apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "camera-cleaner.fullname" . }}-cameras
  labels:
    {{- include "camera-cleaner.labels" . | nindent 4 }}
data:
  cameras.yaml: |
{{ .Values.camerasConfig | indent 4 }}
