apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "camera-cleaner.fullname" . }}-frontend
  labels:
    {{- include "camera-cleaner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "camera-cleaner.selectorLabels" (dict "ctx" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "camera-cleaner.selectorLabels" (dict "ctx" . "component" "frontend") | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ include "camera-cleaner.image" (dict "ctx" . "img" .Values.image.frontend) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
