// The 80 COCO classes that YOLO / OpenVINO can detect, in class-ID order.
// `id` is the YOLO class index (passed to the model's `classes=` param so it
// only looks for the selected objects). `ru` is the Russian label shown in the
// UI. `emoji` is the authoritative emoji for each class — used by aiHelpers.js.
export const COCO_CLASSES = [
  { id: 0,  en: 'person',         ru: 'человек',              emoji: '🚶' },
  { id: 1,  en: 'bicycle',        ru: 'велосипед',            emoji: '🚲' },
  { id: 2,  en: 'car',            ru: 'машина',               emoji: '🚗' },
  { id: 3,  en: 'motorcycle',     ru: 'мотоцикл',             emoji: '🏍️' },
  { id: 4,  en: 'airplane',       ru: 'самолёт',              emoji: '✈️' },
  { id: 5,  en: 'bus',            ru: 'автобус',              emoji: '🚌' },
  { id: 6,  en: 'train',          ru: 'поезд',                emoji: '🚆' },
  { id: 7,  en: 'truck',          ru: 'грузовик',             emoji: '🚛' },
  { id: 8,  en: 'boat',           ru: 'лодка',                emoji: '🚤' },
  { id: 9,  en: 'traffic light',  ru: 'светофор',             emoji: '🚦' },
  { id: 10, en: 'fire hydrant',   ru: 'гидрант',              emoji: '🧯' },
  { id: 11, en: 'stop sign',      ru: 'знак стоп',            emoji: '🛑' },
  { id: 12, en: 'parking meter',  ru: 'паркомат',             emoji: '🅿️' },
  { id: 13, en: 'bench',          ru: 'скамейка',             emoji: '🪑' },
  { id: 14, en: 'bird',           ru: 'птица',                emoji: '🐦' },
  { id: 15, en: 'cat',            ru: 'кошка',                emoji: '🐱' },
  { id: 16, en: 'dog',            ru: 'собака',               emoji: '🐕' },
  { id: 17, en: 'horse',          ru: 'лошадь',               emoji: '🐴' },
  { id: 18, en: 'sheep',          ru: 'овца',                 emoji: '🐑' },
  { id: 19, en: 'cow',            ru: 'корова',               emoji: '🐄' },
  { id: 20, en: 'elephant',       ru: 'слон',                 emoji: '🐘' },
  { id: 21, en: 'bear',           ru: 'медведь',              emoji: '🐻' },
  { id: 22, en: 'zebra',          ru: 'зебра',                emoji: '🦓' },
  { id: 23, en: 'giraffe',        ru: 'жираф',                emoji: '🦒' },
  { id: 24, en: 'backpack',       ru: 'рюкзак',               emoji: '🎒' },
  { id: 25, en: 'umbrella',       ru: 'зонт',                 emoji: '☂️' },
  { id: 26, en: 'handbag',        ru: 'сумка',                emoji: '👜' },
  { id: 27, en: 'tie',            ru: 'галстук',              emoji: '👔' },
  { id: 28, en: 'suitcase',       ru: 'чемодан',              emoji: '🧳' },
  { id: 29, en: 'frisbee',        ru: 'фрисби',               emoji: '🥏' },
  { id: 30, en: 'skis',           ru: 'лыжи',                 emoji: '⛷️' },
  { id: 31, en: 'snowboard',      ru: 'сноуборд',             emoji: '🏂' },
  { id: 32, en: 'sports ball',    ru: 'мяч',                  emoji: '⚽' },
  { id: 33, en: 'kite',           ru: 'воздушный змей',       emoji: '🪁' },
  { id: 34, en: 'baseball bat',   ru: 'бейсбольная бита',     emoji: '🏏' },
  { id: 35, en: 'baseball glove', ru: 'бейсбольная перчатка', emoji: '⚾' },
  { id: 36, en: 'skateboard',     ru: 'скейтборд',            emoji: '🛹' },
  { id: 37, en: 'surfboard',      ru: 'доска для сёрфинга',   emoji: '🏄' },
  { id: 38, en: 'tennis racket',  ru: 'теннисная ракетка',    emoji: '🎾' },
  { id: 39, en: 'bottle',         ru: 'бутылка',              emoji: '🍶' },
  { id: 40, en: 'wine glass',     ru: 'бокал',                emoji: '🍷' },
  { id: 41, en: 'cup',            ru: 'чашка',                emoji: '☕' },
  { id: 42, en: 'fork',           ru: 'вилка',                emoji: '🍴' },
  { id: 43, en: 'knife',          ru: 'нож',                  emoji: '🔪' },
  { id: 44, en: 'spoon',          ru: 'ложка',                emoji: '🥄' },
  { id: 45, en: 'bowl',           ru: 'миска',                emoji: '🥣' },
  { id: 46, en: 'banana',         ru: 'банан',                emoji: '🍌' },
  { id: 47, en: 'apple',          ru: 'яблоко',               emoji: '🍎' },
  { id: 48, en: 'sandwich',       ru: 'сэндвич',              emoji: '🥪' },
  { id: 49, en: 'orange',         ru: 'апельсин',             emoji: '🍊' },
  { id: 50, en: 'broccoli',       ru: 'брокколи',             emoji: '🥦' },
  { id: 51, en: 'carrot',         ru: 'морковь',              emoji: '🥕' },
  { id: 52, en: 'hot dog',        ru: 'хот-дог',              emoji: '🌭' },
  { id: 53, en: 'pizza',          ru: 'пицца',                emoji: '🍕' },
  { id: 54, en: 'donut',          ru: 'пончик',               emoji: '🍩' },
  { id: 55, en: 'cake',           ru: 'торт',                 emoji: '🎂' },
  { id: 56, en: 'chair',          ru: 'стул',                 emoji: '🪑' },
  { id: 57, en: 'couch',          ru: 'диван',                emoji: '🛋️' },
  { id: 58, en: 'potted plant',   ru: 'растение в горшке',    emoji: '🪴' },
  { id: 59, en: 'bed',            ru: 'кровать',              emoji: '🛏️' },
  { id: 60, en: 'dining table',   ru: 'обеденный стол',       emoji: '🍽️' },
  { id: 61, en: 'toilet',         ru: 'туалет',               emoji: '🚽' },
  { id: 62, en: 'tv',             ru: 'телевизор',            emoji: '📺' },
  { id: 63, en: 'laptop',         ru: 'ноутбук',              emoji: '💻' },
  { id: 64, en: 'mouse',          ru: 'мышь',                 emoji: '🖱️' },
  { id: 65, en: 'remote',         ru: 'пульт',                emoji: '📺' },
  { id: 66, en: 'keyboard',       ru: 'клавиатура',           emoji: '⌨️' },
  { id: 67, en: 'cell phone',     ru: 'телефон',              emoji: '📱' },
  { id: 68, en: 'microwave',      ru: 'микроволновка',        emoji: '📦' },
  { id: 69, en: 'oven',           ru: 'духовка',              emoji: '🍳' },
  { id: 70, en: 'toaster',        ru: 'тостер',               emoji: '🍞' },
  { id: 71, en: 'sink',           ru: 'раковина',             emoji: '🚿' },
  { id: 72, en: 'refrigerator',   ru: 'холодильник',          emoji: '🧊' },
  { id: 73, en: 'book',           ru: 'книга',                emoji: '📚' },
  { id: 74, en: 'clock',          ru: 'часы',                 emoji: '⏰' },
  { id: 75, en: 'vase',           ru: 'ваза',                 emoji: '🏺' },
  { id: 76, en: 'scissors',       ru: 'ножницы',              emoji: '✂️' },
  { id: 77, en: 'teddy bear',     ru: 'плюшевый мишка',       emoji: '🧸' },
  { id: 78, en: 'hair drier',     ru: 'фен',                  emoji: '💨' },
  { id: 79, en: 'toothbrush',     ru: 'зубная щётка',         emoji: '🪥' },
]

// Default detected classes: человек, птица, кошка, собака, рюкзак, сумка.
export const DETECTION_CLASSES_DEFAULT = [0, 14, 15, 16, 24, 26]
