name: Camera Archive Cleaner
description: Browse, review, and clean camera archive files from a network share.
version: "1.1.19"
slug: camera_archive_cleaner
arch:
  - amd64
  - aarch64
ingress: true
ingress_port: 8099
panel_icon: mdi:cctv
map:
  - media:rw
image: ghcr.io/sergeyanokhin/camera-archive-cleaner-addon
startup: application
